Terrafrom module for Azure
yugabyte/terraform-azure-yugabyte pull request #1
Opened 2019-07-15 07:06 UTC by vp15591

A terraform module for deploying YugaByte DB cluster in Azure cloud. By default, it will create a three-node cluster in azure. While deployment it will create a virtual network with three subnets. All nodes will be deployed in multiple availability zones. By default replication factor is also set to three.

2019-07-23 22:46 UTC, andrewc-dev requested changes
Where should the credentials and the module mentioned in the README be stored? Is this supposed to be a `terraform.tfvars` file?
Also, I'm seeing an error when I try to run `terraform plan` in the repository:
<img width="592" alt="Screen Shot 2019-07-23 at 3 43 05 PM" src="https://user-images.githubusercontent.com/50115930/61752572-fc210980-ad60-11e9-9609-b840151fc633.png">

2019-07-24 19:02 UTC, ramkumarvs requested changes
Also when i tried running the terraform on the azure shell, it gave this error. Some where looks like we are using current user name

/home/kannan/yugabyte-db/tserver/conf/server.conf: No such file or directory

2019-07-24 19:02 UTC, ramkumarvs commented on main.tf
> +            type = "ssh"
in latest terraform, you need to provide the host value. Otherwise it would fail, please update that in all provider calls

2019-07-24 19:02 UTC, ramkumarvs commented on variables.tf
> +  default     = "us-west1"
this is a not a valid Azure region

2019-07-31 08:48 UTC, vp15591 commented on variables.tf
> +  default     = "us-west1"
update the default region

2019-07-31 08:53 UTC, vp15591 commented on main.tf
> +            type = "ssh"
I have updated the module to support the terraform latest module.

2019-08-02 06:03 UTC, merged